// Code generated by protoc-gen-go. DO NOT EDIT.
// source: annotated.proto

package testdata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Foo struct {
	A                    string   `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	Bar                  *Bar     `protobuf:"bytes,2,opt,name=bar,proto3" json:"bar,omitempty"`
	Req                  string   `protobuf:"bytes,3,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Foo) Reset()         { *m = Foo{} }
func (m *Foo) String() string { return proto.CompactTextString(m) }
func (*Foo) ProtoMessage()    {}
func (*Foo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e975ae609bc8c7, []int{0}
}

func (m *Foo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Foo.Unmarshal(m, b)
}
func (m *Foo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Foo.Marshal(b, m, deterministic)
}
func (m *Foo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Foo.Merge(m, src)
}
func (m *Foo) XXX_Size() int {
	return xxx_messageInfo_Foo.Size(m)
}
func (m *Foo) XXX_DiscardUnknown() {
	xxx_messageInfo_Foo.DiscardUnknown(m)
}

var xxx_messageInfo_Foo proto.InternalMessageInfo

func (m *Foo) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

func (m *Foo) GetBar() *Bar {
	if m != nil {
		return m.Bar
	}
	return nil
}

func (m *Foo) GetReq() string {
	if m != nil {
		return m.Req
	}
	return ""
}

type Bar struct {
	B                    string   `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	Baz                  *Baz     `protobuf:"bytes,2,opt,name=baz,proto3" json:"baz,omitempty"`
	A                    string   `protobuf:"bytes,3,opt,name=a,proto3" json:"a,omitempty"`
	Def                  string   `protobuf:"bytes,4,opt,name=def,proto3" json:"def,omitempty"`
	Remote               string   `protobuf:"bytes,5,opt,name=remote,proto3" json:"remote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bar) Reset()         { *m = Bar{} }
func (m *Bar) String() string { return proto.CompactTextString(m) }
func (*Bar) ProtoMessage()    {}
func (*Bar) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e975ae609bc8c7, []int{1}
}

func (m *Bar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bar.Unmarshal(m, b)
}
func (m *Bar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bar.Marshal(b, m, deterministic)
}
func (m *Bar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bar.Merge(m, src)
}
func (m *Bar) XXX_Size() int {
	return xxx_messageInfo_Bar.Size(m)
}
func (m *Bar) XXX_DiscardUnknown() {
	xxx_messageInfo_Bar.DiscardUnknown(m)
}

var xxx_messageInfo_Bar proto.InternalMessageInfo

func (m *Bar) GetB() string {
	if m != nil {
		return m.B
	}
	return ""
}

func (m *Bar) GetBaz() *Baz {
	if m != nil {
		return m.Baz
	}
	return nil
}

func (m *Bar) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

func (m *Bar) GetDef() string {
	if m != nil {
		return m.Def
	}
	return ""
}

func (m *Bar) GetRemote() string {
	if m != nil {
		return m.Remote
	}
	return ""
}

type Baz struct {
	C                    string   `protobuf:"bytes,1,opt,name=c,proto3" json:"c,omitempty"`
	Biz                  []*Biz   `protobuf:"bytes,2,rep,name=biz,proto3" json:"biz,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Baz) Reset()         { *m = Baz{} }
func (m *Baz) String() string { return proto.CompactTextString(m) }
func (*Baz) ProtoMessage()    {}
func (*Baz) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e975ae609bc8c7, []int{2}
}

func (m *Baz) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Baz.Unmarshal(m, b)
}
func (m *Baz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Baz.Marshal(b, m, deterministic)
}
func (m *Baz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Baz.Merge(m, src)
}
func (m *Baz) XXX_Size() int {
	return xxx_messageInfo_Baz.Size(m)
}
func (m *Baz) XXX_DiscardUnknown() {
	xxx_messageInfo_Baz.DiscardUnknown(m)
}

var xxx_messageInfo_Baz proto.InternalMessageInfo

func (m *Baz) GetC() string {
	if m != nil {
		return m.C
	}
	return ""
}

func (m *Baz) GetBiz() []*Biz {
	if m != nil {
		return m.Biz
	}
	return nil
}

type Biz struct {
	D                    string   `protobuf:"bytes,1,opt,name=d,proto3" json:"d,omitempty"`
	E                    string   `protobuf:"bytes,2,opt,name=e,proto3" json:"e,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Biz) Reset()         { *m = Biz{} }
func (m *Biz) String() string { return proto.CompactTextString(m) }
func (*Biz) ProtoMessage()    {}
func (*Biz) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e975ae609bc8c7, []int{3}
}

func (m *Biz) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Biz.Unmarshal(m, b)
}
func (m *Biz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Biz.Marshal(b, m, deterministic)
}
func (m *Biz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Biz.Merge(m, src)
}
func (m *Biz) XXX_Size() int {
	return xxx_messageInfo_Biz.Size(m)
}
func (m *Biz) XXX_DiscardUnknown() {
	xxx_messageInfo_Biz.DiscardUnknown(m)
}

var xxx_messageInfo_Biz proto.InternalMessageInfo

func (m *Biz) GetD() string {
	if m != nil {
		return m.D
	}
	return ""
}

func (m *Biz) GetE() string {
	if m != nil {
		return m.E
	}
	return ""
}

type Qux struct {
	Req                  string   `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	E                    string   `protobuf:"bytes,2,opt,name=e,proto3" json:"e,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Qux) Reset()         { *m = Qux{} }
func (m *Qux) String() string { return proto.CompactTextString(m) }
func (*Qux) ProtoMessage()    {}
func (*Qux) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e975ae609bc8c7, []int{4}
}

func (m *Qux) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Qux.Unmarshal(m, b)
}
func (m *Qux) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Qux.Marshal(b, m, deterministic)
}
func (m *Qux) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Qux.Merge(m, src)
}
func (m *Qux) XXX_Size() int {
	return xxx_messageInfo_Qux.Size(m)
}
func (m *Qux) XXX_DiscardUnknown() {
	xxx_messageInfo_Qux.DiscardUnknown(m)
}

var xxx_messageInfo_Qux proto.InternalMessageInfo

func (m *Qux) GetReq() string {
	if m != nil {
		return m.Req
	}
	return ""
}

func (m *Qux) GetE() string {
	if m != nil {
		return m.E
	}
	return ""
}

type Wibble struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wibble) Reset()         { *m = Wibble{} }
func (m *Wibble) String() string { return proto.CompactTextString(m) }
func (*Wibble) ProtoMessage()    {}
func (*Wibble) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e975ae609bc8c7, []int{5}
}

func (m *Wibble) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wibble.Unmarshal(m, b)
}
func (m *Wibble) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wibble.Marshal(b, m, deterministic)
}
func (m *Wibble) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wibble.Merge(m, src)
}
func (m *Wibble) XXX_Size() int {
	return xxx_messageInfo_Wibble.Size(m)
}
func (m *Wibble) XXX_DiscardUnknown() {
	xxx_messageInfo_Wibble.DiscardUnknown(m)
}

var xxx_messageInfo_Wibble proto.InternalMessageInfo

type Wobble struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wobble) Reset()         { *m = Wobble{} }
func (m *Wobble) String() string { return proto.CompactTextString(m) }
func (*Wobble) ProtoMessage()    {}
func (*Wobble) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e975ae609bc8c7, []int{6}
}

func (m *Wobble) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wobble.Unmarshal(m, b)
}
func (m *Wobble) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wobble.Marshal(b, m, deterministic)
}
func (m *Wobble) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wobble.Merge(m, src)
}
func (m *Wobble) XXX_Size() int {
	return xxx_messageInfo_Wobble.Size(m)
}
func (m *Wobble) XXX_DiscardUnknown() {
	xxx_messageInfo_Wobble.DiscardUnknown(m)
}

var xxx_messageInfo_Wobble proto.InternalMessageInfo

func (m *Wobble) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Wubble struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wubble) Reset()         { *m = Wubble{} }
func (m *Wubble) String() string { return proto.CompactTextString(m) }
func (*Wubble) ProtoMessage()    {}
func (*Wubble) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e975ae609bc8c7, []int{7}
}

func (m *Wubble) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wubble.Unmarshal(m, b)
}
func (m *Wubble) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wubble.Marshal(b, m, deterministic)
}
func (m *Wubble) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wubble.Merge(m, src)
}
func (m *Wubble) XXX_Size() int {
	return xxx_messageInfo_Wubble.Size(m)
}
func (m *Wubble) XXX_DiscardUnknown() {
	xxx_messageInfo_Wubble.DiscardUnknown(m)
}

var xxx_messageInfo_Wubble proto.InternalMessageInfo

func (m *Wubble) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Flob struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Flob) Reset()         { *m = Flob{} }
func (m *Flob) String() string { return proto.CompactTextString(m) }
func (*Flob) ProtoMessage()    {}
func (*Flob) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e975ae609bc8c7, []int{8}
}

func (m *Flob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flob.Unmarshal(m, b)
}
func (m *Flob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flob.Marshal(b, m, deterministic)
}
func (m *Flob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flob.Merge(m, src)
}
func (m *Flob) XXX_Size() int {
	return xxx_messageInfo_Flob.Size(m)
}
func (m *Flob) XXX_DiscardUnknown() {
	xxx_messageInfo_Flob.DiscardUnknown(m)
}

var xxx_messageInfo_Flob proto.InternalMessageInfo

func (m *Flob) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Foo)(nil), "annotated.Foo")
	proto.RegisterType((*Bar)(nil), "annotated.Bar")
	proto.RegisterType((*Baz)(nil), "annotated.Baz")
	proto.RegisterType((*Biz)(nil), "annotated.Biz")
	proto.RegisterType((*Qux)(nil), "annotated.Qux")
	proto.RegisterType((*Wibble)(nil), "annotated.Wibble")
	proto.RegisterType((*Wobble)(nil), "annotated.Wobble")
	proto.RegisterType((*Wubble)(nil), "annotated.Wubble")
	proto.RegisterType((*Flob)(nil), "annotated.Flob")
}

func init() { proto.RegisterFile("annotated.proto", fileDescriptor_e9e975ae609bc8c7) }

var fileDescriptor_e9e975ae609bc8c7 = []byte{
	// 544 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x4d, 0x6f, 0xd3, 0x30,
	0x1c, 0xc6, 0xf1, 0xb2, 0x56, 0xcc, 0xa0, 0xbd, 0xb8, 0x63, 0x84, 0x0a, 0x89, 0x12, 0x09, 0x69,
	0x97, 0xc5, 0xb0, 0x69, 0x97, 0xc2, 0x25, 0x39, 0xf4, 0x8a, 0x16, 0x0e, 0x95, 0xb8, 0x54, 0x76,
	0xec, 0x64, 0x86, 0x34, 0xff, 0xe0, 0xb8, 0x15, 0xa4, 0xaa, 0x38, 0xf0, 0x15, 0xb8, 0x71, 0xe0,
	0x9b, 0xf0, 0x59, 0x38, 0xf7, 0x23, 0xf4, 0x84, 0x9c, 0xa4, 0x0c, 0x41, 0x77, 0xe4, 0xf6, 0xf4,
	0xf9, 0xbf, 0xf4, 0xf7, 0xd8, 0x31, 0x3e, 0x60, 0x79, 0x0e, 0x86, 0x19, 0x29, 0xfc, 0x42, 0x83,
	0x01, 0xb2, 0xf7, 0xdb, 0xe8, 0x3f, 0x49, 0x01, 0xd2, 0x4c, 0x52, 0x56, 0x28, 0x9a, 0x28, 0x99,
	0x89, 0x09, 0x97, 0xd7, 0x6c, 0xae, 0x40, 0x37, 0xbd, 0xfd, 0x47, 0x7f, 0x34, 0x68, 0x59, 0xc2,
	0x4c, 0xc7, 0xb2, 0x29, 0x79, 0x5f, 0x10, 0x76, 0x46, 0x00, 0xe4, 0x3e, 0x46, 0xcc, 0x45, 0x03,
	0x74, 0xba, 0x17, 0x21, 0x46, 0x06, 0xd8, 0xe1, 0x4c, 0xbb, 0x3b, 0x03, 0x74, 0x7a, 0xef, 0x7c,
	0xdf, 0xbf, 0xf9, 0xef, 0x90, 0xe9, 0xc8, 0x96, 0xc8, 0x03, 0xec, 0x68, 0xf9, 0xc1, 0x75, 0xec,
	0x44, 0xe8, 0xfc, 0x0c, 0x76, 0x22, 0xfb, 0x7b, 0x78, 0xb9, 0x0a, 0xce, 0xf1, 0x41, 0x02, 0xe0,
	0x73, 0xa6, 0xfd, 0x18, 0xa6, 0xd4, 0x2e, 0x7f, 0x5c, 0x68, 0x78, 0x27, 0x63, 0x53, 0xd2, 0x45,
	0xab, 0x96, 0x34, 0x01, 0xa0, 0x8b, 0x04, 0x60, 0xd9, 0x47, 0xcc, 0xfb, 0x8a, 0xb0, 0x13, 0x32,
	0x4d, 0x8e, 0x30, 0xe2, 0x0d, 0x85, 0xdd, 0x89, 0x22, 0xc4, 0x1b, 0x94, 0x6a, 0x2b, 0x4a, 0x65,
	0x51, 0x2a, 0x72, 0x62, 0xd1, 0x1b, 0x90, 0xbb, 0xeb, 0xa0, 0x53, 0xe7, 0xb1, 0x21, 0x0e, 0xb1,
	0x23, 0x64, 0xe2, 0xee, 0xd6, 0xa1, 0xac, 0x24, 0x3e, 0xee, 0x6a, 0x39, 0x05, 0x23, 0xdd, 0x4e,
	0xdd, 0x7e, 0xb2, 0x0e, 0x7a, 0xe4, 0x48, 0xc8, 0x44, 0xe5, 0xca, 0x28, 0xc8, 0xfd, 0x11, 0x80,
	0x4d, 0xd8, 0x76, 0x79, 0xaf, 0x2c, 0x55, 0x45, 0x7a, 0x18, 0xc5, 0x2d, 0x55, 0x67, 0x1d, 0xec,
	0xe0, 0x3b, 0x11, 0x8a, 0x6b, 0x2e, 0x65, 0xb9, 0x9c, 0xbf, 0xb9, 0x94, 0xe5, 0x52, 0x95, 0x77,
	0x89, 0x9d, 0x50, 0xd5, 0x78, 0xa2, 0x9d, 0x6e, 0xf0, 0xc2, 0x59, 0x15, 0x21, 0x61, 0x7d, 0x59,
	0xc7, 0xda, 0xf8, 0x57, 0xb3, 0x8f, 0x11, 0x92, 0xde, 0xb3, 0x5a, 0x59, 0x7a, 0x7b, 0xc0, 0xcd,
	0x95, 0x58, 0x69, 0xaf, 0xa8, 0x1d, 0xb0, 0x6d, 0x4f, 0x71, 0x77, 0xac, 0x38, 0xcf, 0xe4, 0xf0,
	0xe1, 0x2a, 0x38, 0xc6, 0x84, 0xf1, 0xd8, 0x17, 0x32, 0xa9, 0xcf, 0xbc, 0x29, 0x78, 0x2f, 0x70,
	0x77, 0x0c, 0x56, 0x11, 0x82, 0x77, 0x73, 0x36, 0x95, 0xed, 0xb6, 0x5a, 0x0f, 0x7b, 0xab, 0xe0,
	0x90, 0xec, 0x4f, 0x55, 0x59, 0xaa, 0x3c, 0xa5, 0x0b, 0xf3, 0xa9, 0x90, 0x4b, 0xef, 0x07, 0xc2,
	0xdd, 0xf1, 0xec, 0xd6, 0x99, 0xef, 0x68, 0x15, 0x7c, 0x43, 0xf8, 0x33, 0x67, 0x62, 0xf3, 0x1d,
	0x4d, 0xec, 0xe0, 0xe4, 0xbd, 0xca, 0x05, 0xdd, 0xea, 0xfe, 0x0f, 0x93, 0xb8, 0x9c, 0x09, 0xba,
	0xf8, 0xb7, 0xb0, 0xf4, 0x5e, 0xe3, 0xdd, 0x51, 0x06, 0x7c, 0x2b, 0xfd, 0xc5, 0x2a, 0x78, 0x8e,
	0x8f, 0xdb, 0xc4, 0x93, 0x52, 0xea, 0xb9, 0x8a, 0xe5, 0xc4, 0x96, 0x6e, 0x5f, 0x18, 0xbe, 0x79,
	0x7b, 0x95, 0x2a, 0x73, 0x3d, 0xe3, 0xf5, 0xc9, 0x36, 0x0f, 0x89, 0x15, 0xaa, 0xa4, 0x29, 0x2b,
	0x54, 0x7c, 0x16, 0x43, 0x9e, 0xa8, 0xf4, 0x6c, 0xce, 0x32, 0x25, 0x98, 0x01, 0x4d, 0x55, 0x6e,
	0xa4, 0xce, 0x59, 0x46, 0x6f, 0x2c, 0x23, 0x4b, 0x23, 0x98, 0x61, 0x2f, 0x37, 0x82, 0x77, 0xeb,
	0xc7, 0x77, 0xf1, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x98, 0x8a, 0x8d, 0xd6, 0x03, 0x00, 0x00,
}
