// Code generated by protoc-gen-go. DO NOT EDIT.
// source: annotated.proto

package testdata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Foo struct {
	A                    string   `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	Bar                  *Bar     `protobuf:"bytes,2,opt,name=bar,proto3" json:"bar,omitempty"`
	Req                  string   `protobuf:"bytes,3,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Foo) Reset()         { *m = Foo{} }
func (m *Foo) String() string { return proto.CompactTextString(m) }
func (*Foo) ProtoMessage()    {}
func (*Foo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e975ae609bc8c7, []int{0}
}

func (m *Foo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Foo.Unmarshal(m, b)
}
func (m *Foo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Foo.Marshal(b, m, deterministic)
}
func (m *Foo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Foo.Merge(m, src)
}
func (m *Foo) XXX_Size() int {
	return xxx_messageInfo_Foo.Size(m)
}
func (m *Foo) XXX_DiscardUnknown() {
	xxx_messageInfo_Foo.DiscardUnknown(m)
}

var xxx_messageInfo_Foo proto.InternalMessageInfo

func (m *Foo) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

func (m *Foo) GetBar() *Bar {
	if m != nil {
		return m.Bar
	}
	return nil
}

func (m *Foo) GetReq() string {
	if m != nil {
		return m.Req
	}
	return ""
}

type Bar struct {
	B                    string   `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
	Baz                  *Baz     `protobuf:"bytes,2,opt,name=baz,proto3" json:"baz,omitempty"`
	A                    string   `protobuf:"bytes,3,opt,name=a,proto3" json:"a,omitempty"`
	Def                  string   `protobuf:"bytes,4,opt,name=def,proto3" json:"def,omitempty"`
	Remote               string   `protobuf:"bytes,5,opt,name=remote,proto3" json:"remote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bar) Reset()         { *m = Bar{} }
func (m *Bar) String() string { return proto.CompactTextString(m) }
func (*Bar) ProtoMessage()    {}
func (*Bar) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e975ae609bc8c7, []int{1}
}

func (m *Bar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bar.Unmarshal(m, b)
}
func (m *Bar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bar.Marshal(b, m, deterministic)
}
func (m *Bar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bar.Merge(m, src)
}
func (m *Bar) XXX_Size() int {
	return xxx_messageInfo_Bar.Size(m)
}
func (m *Bar) XXX_DiscardUnknown() {
	xxx_messageInfo_Bar.DiscardUnknown(m)
}

var xxx_messageInfo_Bar proto.InternalMessageInfo

func (m *Bar) GetB() string {
	if m != nil {
		return m.B
	}
	return ""
}

func (m *Bar) GetBaz() *Baz {
	if m != nil {
		return m.Baz
	}
	return nil
}

func (m *Bar) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

func (m *Bar) GetDef() string {
	if m != nil {
		return m.Def
	}
	return ""
}

func (m *Bar) GetRemote() string {
	if m != nil {
		return m.Remote
	}
	return ""
}

type Baz struct {
	C                    string   `protobuf:"bytes,1,opt,name=c,proto3" json:"c,omitempty"`
	Biz                  []*Biz   `protobuf:"bytes,2,rep,name=biz,proto3" json:"biz,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Baz) Reset()         { *m = Baz{} }
func (m *Baz) String() string { return proto.CompactTextString(m) }
func (*Baz) ProtoMessage()    {}
func (*Baz) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e975ae609bc8c7, []int{2}
}

func (m *Baz) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Baz.Unmarshal(m, b)
}
func (m *Baz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Baz.Marshal(b, m, deterministic)
}
func (m *Baz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Baz.Merge(m, src)
}
func (m *Baz) XXX_Size() int {
	return xxx_messageInfo_Baz.Size(m)
}
func (m *Baz) XXX_DiscardUnknown() {
	xxx_messageInfo_Baz.DiscardUnknown(m)
}

var xxx_messageInfo_Baz proto.InternalMessageInfo

func (m *Baz) GetC() string {
	if m != nil {
		return m.C
	}
	return ""
}

func (m *Baz) GetBiz() []*Biz {
	if m != nil {
		return m.Biz
	}
	return nil
}

type Biz struct {
	D                    string   `protobuf:"bytes,1,opt,name=d,proto3" json:"d,omitempty"`
	E                    string   `protobuf:"bytes,2,opt,name=e,proto3" json:"e,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Biz) Reset()         { *m = Biz{} }
func (m *Biz) String() string { return proto.CompactTextString(m) }
func (*Biz) ProtoMessage()    {}
func (*Biz) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e975ae609bc8c7, []int{3}
}

func (m *Biz) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Biz.Unmarshal(m, b)
}
func (m *Biz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Biz.Marshal(b, m, deterministic)
}
func (m *Biz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Biz.Merge(m, src)
}
func (m *Biz) XXX_Size() int {
	return xxx_messageInfo_Biz.Size(m)
}
func (m *Biz) XXX_DiscardUnknown() {
	xxx_messageInfo_Biz.DiscardUnknown(m)
}

var xxx_messageInfo_Biz proto.InternalMessageInfo

func (m *Biz) GetD() string {
	if m != nil {
		return m.D
	}
	return ""
}

func (m *Biz) GetE() string {
	if m != nil {
		return m.E
	}
	return ""
}

type Qux struct {
	Req                  string   `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	E                    string   `protobuf:"bytes,2,opt,name=e,proto3" json:"e,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Qux) Reset()         { *m = Qux{} }
func (m *Qux) String() string { return proto.CompactTextString(m) }
func (*Qux) ProtoMessage()    {}
func (*Qux) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9e975ae609bc8c7, []int{4}
}

func (m *Qux) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Qux.Unmarshal(m, b)
}
func (m *Qux) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Qux.Marshal(b, m, deterministic)
}
func (m *Qux) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Qux.Merge(m, src)
}
func (m *Qux) XXX_Size() int {
	return xxx_messageInfo_Qux.Size(m)
}
func (m *Qux) XXX_DiscardUnknown() {
	xxx_messageInfo_Qux.DiscardUnknown(m)
}

var xxx_messageInfo_Qux proto.InternalMessageInfo

func (m *Qux) GetReq() string {
	if m != nil {
		return m.Req
	}
	return ""
}

func (m *Qux) GetE() string {
	if m != nil {
		return m.E
	}
	return ""
}

func init() {
	proto.RegisterType((*Foo)(nil), "annotated.Foo")
	proto.RegisterType((*Bar)(nil), "annotated.Bar")
	proto.RegisterType((*Baz)(nil), "annotated.Baz")
	proto.RegisterType((*Biz)(nil), "annotated.Biz")
	proto.RegisterType((*Qux)(nil), "annotated.Qux")
}

func init() { proto.RegisterFile("annotated.proto", fileDescriptor_e9e975ae609bc8c7) }

var fileDescriptor_e9e975ae609bc8c7 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x6e, 0x13, 0x31,
	0x14, 0x85, 0xeb, 0x98, 0x46, 0x8a, 0x91, 0x40, 0x18, 0x90, 0x86, 0x0a, 0x41, 0x3a, 0x6c, 0xba,
	0x69, 0x2c, 0x7e, 0x56, 0xb0, 0x9a, 0x51, 0xc5, 0xbe, 0x5e, 0xb2, 0x41, 0x9e, 0xf1, 0xf5, 0xd4,
	0x28, 0x9d, 0x3b, 0x38, 0x4e, 0x85, 0x26, 0xca, 0x23, 0xf0, 0x0c, 0xbc, 0x5a, 0xd7, 0x79, 0x84,
	0xac, 0xd0, 0xf5, 0xa4, 0x0d, 0xa0, 0xb0, 0xbb, 0x73, 0xce, 0xf1, 0xf1, 0xe7, 0xb1, 0xc5, 0x63,
	0xd3, 0xb6, 0x18, 0x4d, 0x04, 0x3b, 0xeb, 0x02, 0x46, 0x94, 0x93, 0x7b, 0xe1, 0xe4, 0x75, 0x83,
	0xd8, 0xcc, 0x41, 0x99, 0xce, 0x2b, 0xe7, 0x61, 0x6e, 0xbf, 0x56, 0x70, 0x65, 0x6e, 0x3c, 0x86,
	0x21, 0x7b, 0xf2, 0xe2, 0x8f, 0x40, 0x80, 0x05, 0x2e, 0x43, 0x0d, 0x83, 0x95, 0xa3, 0xe0, 0x9f,
	0x11, 0xa5, 0x12, 0xcc, 0x64, 0x6c, 0xca, 0xce, 0x26, 0xe5, 0xe9, 0xa6, 0x78, 0x25, 0x5e, 0x76,
	0x01, 0xbf, 0x41, 0x1d, 0x17, 0x6a, 0xb5, 0x9b, 0xd6, 0xca, 0x21, 0xaa, 0x95, 0x43, 0x5c, 0x6b,
	0x66, 0xe4, 0x54, 0xf0, 0xca, 0x84, 0x6c, 0x34, 0x65, 0x67, 0x0f, 0xdf, 0x3d, 0x9a, 0xed, 0xe9,
	0x4a, 0x13, 0x34, 0x59, 0xf2, 0xb9, 0xe0, 0x01, 0xbe, 0x67, 0x3c, 0x95, 0xf2, 0xdb, 0x62, 0xa4,
	0xe9, 0x3b, 0xff, 0xc9, 0x04, 0x2f, 0x4d, 0x90, 0x4f, 0x04, 0xab, 0x76, 0x3b, 0xf2, 0xdb, 0x82,
	0x69, 0x56, 0x0d, 0x9d, 0xfd, 0xc1, 0xce, 0x9e, 0x3a, 0x7b, 0xf9, 0x8c, 0x30, 0x87, 0xc6, 0xf1,
	0xb6, 0x20, 0x72, 0x62, 0xc9, 0x04, 0xb7, 0xe0, 0xb2, 0x07, 0xf7, 0xfa, 0x05, 0x38, 0x4d, 0x92,
	0x3c, 0x15, 0xe3, 0x00, 0xd7, 0x18, 0x21, 0x3b, 0x4e, 0xe6, 0x64, 0x5b, 0x8c, 0x75, 0x12, 0xf4,
	0xce, 0xc8, 0x3f, 0x12, 0x4e, 0x4f, 0x38, 0xf5, 0x1d, 0xce, 0xb6, 0x38, 0xd2, 0xac, 0x4e, 0x38,
	0x9e, 0x70, 0xf8, 0xbf, 0x38, 0x9e, 0x70, 0x7c, 0x9f, 0xbf, 0x15, 0xbc, 0xf4, 0x89, 0xca, 0xee,
	0xd6, 0xd2, 0xee, 0xe5, 0xb2, 0xd7, 0xcc, 0x92, 0x0a, 0xe9, 0x2c, 0x83, 0x7a, 0xb9, 0xfc, 0xa1,
	0x19, 0xe4, 0x1f, 0x04, 0x4d, 0x84, 0x4c, 0x3f, 0x87, 0xfd, 0x75, 0x14, 0x92, 0xe4, 0xd3, 0xfd,
	0xb2, 0xe3, 0x4d, 0x31, 0x12, 0x47, 0x9a, 0x41, 0xf9, 0x8b, 0x6d, 0x8a, 0x37, 0x07, 0x2f, 0x25,
	0x80, 0x53, 0xab, 0x00, 0x6e, 0x2d, 0xb9, 0x06, 0xf7, 0xbf, 0x94, 0xa5, 0x94, 0x4d, 0xa9, 0x0b,
	0x70, 0x5f, 0x2e, 0x1b, 0x1f, 0xaf, 0x96, 0xd5, 0xac, 0xc6, 0x6b, 0x35, 0x3c, 0x0d, 0xd3, 0xf9,
	0x85, 0x6a, 0x4c, 0xe7, 0xeb, 0xf3, 0x1a, 0x5b, 0xe7, 0x9b, 0xf3, 0x1b, 0x33, 0xf7, 0xd6, 0x44,
	0x0c, 0xca, 0xb7, 0x11, 0x42, 0x6b, 0xe6, 0x6a, 0x2f, 0x45, 0x58, 0x44, 0x6b, 0xa2, 0xf9, 0x74,
	0x37, 0x54, 0xe3, 0xf4, 0x9c, 0xde, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xfe, 0x1f, 0x21,
	0xa8, 0x02, 0x00, 0x00,
}
