// Code generated by protoc-gen-go. DO NOT EDIT.
// source: basic_test.proto

package testdata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Msg struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3dacebadcaee47d, []int{0}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*Msg)(nil), "basic.Msg")
}

func init() { proto.RegisterFile("basic_test.proto", fileDescriptor_c3dacebadcaee47d) }

var fileDescriptor_c3dacebadcaee47d = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x4a, 0x2c, 0xce,
	0x4c, 0x8e, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x8b,
	0x28, 0xc9, 0x73, 0x31, 0xfb, 0x16, 0xa7, 0x0b, 0x49, 0x70, 0xb1, 0x27, 0xe7, 0xe7, 0x95, 0xa4,
	0xe6, 0x95, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x4e, 0x6a, 0x51, 0x2a, 0x99,
	0x79, 0x25, 0xa9, 0x45, 0x79, 0x89, 0x39, 0xfa, 0x65, 0x89, 0x39, 0x99, 0x29, 0x89, 0x25, 0xf9,
	0x45, 0xfa, 0x20, 0x83, 0x52, 0x12, 0x4b, 0x12, 0xad, 0x61, 0x8c, 0x24, 0x36, 0xb0, 0xb1, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x37, 0xd7, 0x03, 0x45, 0x6a, 0x00, 0x00, 0x00,
}
