version: 2
workflows:
  version: 2
  build_test:
    jobs:
      - build
      - format
jobs:
  format:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run:
          name: Check Format
          command: "! go fmt ./... 2>&1 | read"
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: go test ./...
