---
name: Unit tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.13.1'
    - run: go test ./...
